Add changes for BSD compile and run.
 Changes to be committed:
       modified:   INSTALL

1. Added instructions to install BSD, wrongly noted as "linux".

2. Added note.

       modified:   Makefile

1. Added stdio source as stio for BSD.

2. Set link type static for BSD.

3. Added specific CC, CFLAGS and CPP for BSD.

4. Added CFLAGS for BSD (none).

5. Added libraries for BSD.

6. Add all target for BSD.

7. Changed gcc references to $(CC).

8. Added library components for BSD.

9. Added library builds for BSD.

       modified:   configure

1. Changed shell command to BSD acceptable (and others).

2. Changed from P5 to Petit-ami.

3. Added per OS compiler/bit/host select.

4. Specified packages to install for linux and BSD, and changed package
manager.

5. Removed flip and cpp from check install list, these were P5 stuffs.

6. Change from gcc specific to C compiler.

7. Bracket glibc check for linux only.

       modified:   include/services.h

1. Fix deinitsig() to void.

       modified:   libc/hooktest.c

1. Fix name of deinit().

       modified:   linux/graphics.c

1. Add BSD to __MACH__ lockout defines. These are true for both systems.

2. Many missing returns caught by llvm.

       modified:   linux/services.c

1. Added program path global.

2. Added getpgm() method for BSD.

3. Change deinitsig() to void.

4. Add argc/argv to pa_init_services. Yes, BSD actually supplies this to all
constructors. See notes.

5. In init(), get prgpth from argv[0].

       modified:   linux/terminal.c

1. Add BSD to __MACH__ lockout defines. These are true for both systems.

2. Added putstrc() and putnstrc() routines. These accept signed characters.
This was necessary to stop llvm warnings. Used whereever we have string
literals, which are always signed char.

3. Added strncmpus() routine, that takes second string as signed. This
was necessary to stop llvm warnings.

4. Fixed bad operator association in plcchrext(). This was a serious bug.

5. Fixed many missing returns found by llvm.

6. Added defaults on cases to shut llvm up (hey, sometimes llvm is right,
sometimes just annoying).

       modified:   portable/gnome_widgets.c

1. Added defaults on cases to shut llvm up.

Notes:

1. We found the argc/argv on the constructors and used that to establish the
program path. I have seen this on other systems (windows). This could be used
to establish a portable method for program path.

We can also see if modifying argc/argv here allows passing options to PA
libraries.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1,9 +1,9 @@
-#!/bin/bash
+#!/usr/bin/env bash
 ################################################################################
 #
-# Configure scipt for Pascal-P5
+# Configure scipt for Petit-ami
 #
-# Sets up the complete Pascal-P5 project.
+# Sets up the complete Petit-ami project.
 #
 ################################################################################
 
@@ -33,25 +33,65 @@ function checkexists {
 #
 # Set default variables
 #
-compiler="gcc"
-bits="32"
-host="linux"
+if [ "$(uname)" = "Linux" ]
+then
+
+    compiler="gcc"
+    bits="64"
+    host="linux"
+
+elif [ "$(uname)" = "FreeBSD" ]
+then
+
+    compiler="clang"
+    bits="64"
+    host="bsd"
+
+elif [ "$(uname)" = "Darwin" ]
+then
+
+    compiler="clang"
+    bits="64"
+    host="bsd"
+
+else
+
+    echo "*** Supported operating system not found"
+    exit 1
+
+fi
 
 ################################################################################
 #
 # Make sure used packages are installed.
 #
-sudo apt-get -y install alsa alsa-tools
-sudo apt-get -y install libasound2-dev
-sudo apt-get -y install openssl
-sudo apt-get -y install libssl-dev
-sudo apt-get -y install fluidsynth
-sudo apt-get -y install libfluidsynth-dev
-sudo apt-get -y install gawk
-sudo apt-get -y install bison
-sudo apt-get -y install git
-sudo apt-get -y install openssl
-sudo apt-get -y install libx11-dev
+if [ "$host" = "linux" ]
+then
+
+    sudo apt-get -y install alsa alsa-tools
+    sudo apt-get -y install libasound2-dev
+    sudo apt-get -y install openssl
+    sudo apt-get -y install libssl-dev
+    sudo apt-get -y install fluidsynth
+    sudo apt-get -y install libfluidsynth-dev
+    sudo apt-get -y install gawk
+    sudo apt-get -y install bison
+    sudo apt-get -y install git
+    sudo apt-get -y install openssl
+    sudo apt-get -y install libx11-dev
+
+elif [ "$host" = "bsd" ]
+then
+
+    sudo pkg install openssl
+    sudo pkg install fluidsynth
+    sudo pkg install gawk
+    sudo pkg install bison
+    sudo pkg install git
+    sudo pkg install openssl
+    sudo pkg install gmake
+
+fi
 
 ################################################################################
 #
@@ -69,16 +109,14 @@ checkexists cp
 checkexists mv
 checkexists ls
 checkexists tar
-checkexists flip
-checkexists cpp
 
 #
-# Fail on no gcc found
+# Fail on no C compiler found
 #
-checkexists gcc > /dev/null
+checkexists $compiler > /dev/null
 if [[ $rc != 0 ]] ; then
 
-    echo "*** Aborting: cannot complete without gcc"
+    echo "*** Aborting: cannot complete without known C compiler"
     exit 1
 
 fi
@@ -108,6 +146,11 @@ done
 #
 # Set the version of libc override that is needed.
 #
-setver_glibc
+if [ "$host" = "linux" ]
+then
+
+    setver_glibc
+
+fi
 
 echo "Configure completed!"
